package db;
// Generated Jun 30, 2013 3:06:12 PM by Hibernate Tools 3.2.1.GA



/**
 * Entities generated by hbm2java
 */
public class Entities  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String type;
     private Integer count;

    public Entities() {
    }

    public Entities(String name, String type, Integer count) {
       this.name = name;
       this.type = type;
       this.count = count;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }




}


