package db;
// Generated Jun 19, 2013 5:59:56 AM by Hibernate Tools 3.2.1.GA



/**
 * HyphenatedWords generated by hbm2java
 */
public class HyphenatedWords  implements java.io.Serializable {


     private int id;
     private String hyphenatedWord;
     private String normalWord;

    public HyphenatedWords() {
    }

	
    public HyphenatedWords(int id) {
        this.id = id;
    }
    public HyphenatedWords(int id, String hyphenatedWord, String normalWord) {
       this.id = id;
       this.hyphenatedWord = hyphenatedWord;
       this.normalWord = normalWord;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHyphenatedWord() {
        return this.hyphenatedWord;
    }
    
    public void setHyphenatedWord(String hyphenatedWord) {
        this.hyphenatedWord = hyphenatedWord;
    }
    public String getNormalWord() {
        return this.normalWord;
    }
    
    public void setNormalWord(String normalWord) {
        this.normalWord = normalWord;
    }




}


