package db;
// Generated Jun 30, 2013 3:06:12 PM by Hibernate Tools 3.2.1.GA



/**
 * HyphenatedWords generated by hbm2java
 */
public class HyphenatedWords  implements java.io.Serializable {


     private Integer id;
     private String hyphenatedWord;
     private String normalWord;

    public HyphenatedWords() {
    }

    public HyphenatedWords(String hyphenatedWord, String normalWord) {
       this.hyphenatedWord = hyphenatedWord;
       this.normalWord = normalWord;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getHyphenatedWord() {
        return this.hyphenatedWord;
    }
    
    public void setHyphenatedWord(String hyphenatedWord) {
        this.hyphenatedWord = hyphenatedWord;
    }
    public String getNormalWord() {
        return this.normalWord;
    }
    
    public void setNormalWord(String normalWord) {
        this.normalWord = normalWord;
    }




}


