package db;
// Generated Jun 30, 2013 3:06:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MsAcademicDomains generated by hbm2java
 */
public class MsAcademicDomains  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer domainId;
     private Set msAcademicAuthorses = new HashSet(0);

    public MsAcademicDomains() {
    }

	
    public MsAcademicDomains(String name) {
        this.name = name;
    }
    public MsAcademicDomains(String name, Integer domainId, Set msAcademicAuthorses) {
       this.name = name;
       this.domainId = domainId;
       this.msAcademicAuthorses = msAcademicAuthorses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }
    public Set getMsAcademicAuthorses() {
        return this.msAcademicAuthorses;
    }
    
    public void setMsAcademicAuthorses(Set msAcademicAuthorses) {
        this.msAcademicAuthorses = msAcademicAuthorses;
    }




}


