package db;
// Generated Jun 30, 2013 3:06:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MsAcademicAuthors generated by hbm2java
 */
public class MsAcademicAuthors  implements java.io.Serializable {


     private Integer id;
     private MsAcademicDomains msAcademicDomains;
     private String firstName;
     private String lastName;
     private String middleName;
     private Integer citationCount;
     private Integer publicationCount;
     private Integer GIndex;
     private Integer HIndex;
     private Integer authorId;
     private String homepageUrl;
     private String displayPhotoUrl;
     private Set msAcademicPublicationses = new HashSet(0);

    public MsAcademicAuthors() {
    }

	
    public MsAcademicAuthors(String firstName) {
        this.firstName = firstName;
    }
    public MsAcademicAuthors(MsAcademicDomains msAcademicDomains, String firstName, String lastName, String middleName, Integer citationCount, Integer publicationCount, Integer GIndex, Integer HIndex, Integer authorId, String homepageUrl, String displayPhotoUrl, Set msAcademicPublicationses) {
       this.msAcademicDomains = msAcademicDomains;
       this.firstName = firstName;
       this.lastName = lastName;
       this.middleName = middleName;
       this.citationCount = citationCount;
       this.publicationCount = publicationCount;
       this.GIndex = GIndex;
       this.HIndex = HIndex;
       this.authorId = authorId;
       this.homepageUrl = homepageUrl;
       this.displayPhotoUrl = displayPhotoUrl;
       this.msAcademicPublicationses = msAcademicPublicationses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MsAcademicDomains getMsAcademicDomains() {
        return this.msAcademicDomains;
    }
    
    public void setMsAcademicDomains(MsAcademicDomains msAcademicDomains) {
        this.msAcademicDomains = msAcademicDomains;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public Integer getCitationCount() {
        return this.citationCount;
    }
    
    public void setCitationCount(Integer citationCount) {
        this.citationCount = citationCount;
    }
    public Integer getPublicationCount() {
        return this.publicationCount;
    }
    
    public void setPublicationCount(Integer publicationCount) {
        this.publicationCount = publicationCount;
    }
    public Integer getGIndex() {
        return this.GIndex;
    }
    
    public void setGIndex(Integer GIndex) {
        this.GIndex = GIndex;
    }
    public Integer getHIndex() {
        return this.HIndex;
    }
    
    public void setHIndex(Integer HIndex) {
        this.HIndex = HIndex;
    }
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
    public String getHomepageUrl() {
        return this.homepageUrl;
    }
    
    public void setHomepageUrl(String homepageUrl) {
        this.homepageUrl = homepageUrl;
    }
    public String getDisplayPhotoUrl() {
        return this.displayPhotoUrl;
    }
    
    public void setDisplayPhotoUrl(String displayPhotoUrl) {
        this.displayPhotoUrl = displayPhotoUrl;
    }
    public Set getMsAcademicPublicationses() {
        return this.msAcademicPublicationses;
    }
    
    public void setMsAcademicPublicationses(Set msAcademicPublicationses) {
        this.msAcademicPublicationses = msAcademicPublicationses;
    }




}


