package db;
// Generated Jun 30, 2013 3:06:12 PM by Hibernate Tools 3.2.1.GA



/**
 * MsAcademicPublications generated by hbm2java
 */
public class MsAcademicPublications  implements java.io.Serializable {


     private Integer id;
     private MsAcademicAuthors msAcademicAuthors;
     private String title;
     private Integer year;
     private String fullVersionUrl;
     private String abstract_;
     private String content;
     private String filename;
     private String contentType;
     private Boolean downloaded;
     private Integer citationCount;
     private Integer referenceCount;
     private Integer publicationId;

    public MsAcademicPublications() {
    }

    public MsAcademicPublications(MsAcademicAuthors msAcademicAuthors, String title, Integer year, String fullVersionUrl, String abstract_, String content, String filename, String contentType, Boolean downloaded, Integer citationCount, Integer referenceCount, Integer publicationId) {
       this.msAcademicAuthors = msAcademicAuthors;
       this.title = title;
       this.year = year;
       this.fullVersionUrl = fullVersionUrl;
       this.abstract_ = abstract_;
       this.content = content;
       this.filename = filename;
       this.contentType = contentType;
       this.downloaded = downloaded;
       this.citationCount = citationCount;
       this.referenceCount = referenceCount;
       this.publicationId = publicationId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MsAcademicAuthors getMsAcademicAuthors() {
        return this.msAcademicAuthors;
    }
    
    public void setMsAcademicAuthors(MsAcademicAuthors msAcademicAuthors) {
        this.msAcademicAuthors = msAcademicAuthors;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public String getFullVersionUrl() {
        return this.fullVersionUrl;
    }
    
    public void setFullVersionUrl(String fullVersionUrl) {
        this.fullVersionUrl = fullVersionUrl;
    }
    public String getAbstract_() {
        return this.abstract_;
    }
    
    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }
    public Boolean getDownloaded() {
        return this.downloaded;
    }
    
    public void setDownloaded(Boolean downloaded) {
        this.downloaded = downloaded;
    }
    public Integer getCitationCount() {
        return this.citationCount;
    }
    
    public void setCitationCount(Integer citationCount) {
        this.citationCount = citationCount;
    }
    public Integer getReferenceCount() {
        return this.referenceCount;
    }
    
    public void setReferenceCount(Integer referenceCount) {
        this.referenceCount = referenceCount;
    }
    public Integer getPublicationId() {
        return this.publicationId;
    }
    
    public void setPublicationId(Integer publicationId) {
        this.publicationId = publicationId;
    }




}


